#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ph.Mobext.Sureseats.AndroidApp.Resource", IsApplication=true)]

namespace Ph.Mobext.Sureseats.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_down = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_in_left = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_out_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_right = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_up = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ayala_logo_large = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_body = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_header = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_home_arc = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_logIn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_screenTitle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_xml_border_with_stroke = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_xml_normal_border_orange = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_xml_normal_border_silver = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_xml_round_border = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_xml_round_border_beige = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_xml_round_border_bottom = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg_xml_round_border_bottom_with_stroke = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bg_xml_round_border_darkOrange = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bg_xml_round_border_green = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bg_xml_round_border_orange = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bg_xml_round_border_top = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bg_xml_round_border_top_with_stroke = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int dialogBorder = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int dude = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_account_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_account_pressed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_check_in_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_check_in_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_gesture_slide = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_gesture_zoom = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_info = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_left = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_logo = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_movie_normal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_movie_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_navigate = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_reserve = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_right = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_search = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_star_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_star_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Icon = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int img_AfterEarth = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int img_Gijoe = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int img_IronMan3 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int img_Oz = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int qr_sample = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int testing = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070025
			public const int CheckIn_spnSelectMovie = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int CheckIn_spn_SelectCinema = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int CheckIn_tvAt = 2131165222;
			
			// aapt resource value: 0x7f070028
			public const int CheckIn_tvCheckIn = 2131165224;
			
			// aapt resource value: 0x7f070024
			public const int CheckIn_tvImWatching = 2131165220;
			
			// aapt resource value: 0x7f070019
			public const int Instruction_imgGestureZoom = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int Instruction_tvReserveSeats = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int Instruction_tvTitle = 2131165208;
			
			// aapt resource value: 0x7f070029
			public const int LogInOne_etEmailAddress = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int LogInOne_etPassword = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int LogInOne_tvLogIn = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int LogInOne_tvNotYou = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int LogInTwo_tvContinue = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int LogInTwo_tvLoggedAs = 2131165228;
			
			// aapt resource value: 0x7f070001
			public const int LoginMaster_Title = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int LoginMaster_fraContent = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int LoginMaster_imgLogo = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int LoginMaster_tvContactUs = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int LoginMaster_tvDiv = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int LoginMaster_tvHelp = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int LoginMaster_tvRegister = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int LoginMaster_tvStillDontHaveAnAccount = 2131165187;
			
			// aapt resource value: 0x7f07004e
			public const int MDS_fraLayout = 2131165262;
			
			// aapt resource value: 0x7f070048
			public const int MDS_linDetail = 2131165256;
			
			// aapt resource value: 0x7f07004f
			public const int MDS_linDetailContent = 2131165263;
			
			// aapt resource value: 0x7f07004a
			public const int MDS_linSchedule = 2131165258;
			
			// aapt resource value: 0x7f070050
			public const int MDS_linScheduleContent = 2131165264;
			
			// aapt resource value: 0x7f07004c
			public const int MDS_linTrailer = 2131165260;
			
			// aapt resource value: 0x7f070051
			public const int MDS_linTrailerContent = 2131165265;
			
			// aapt resource value: 0x7f070049
			public const int MDS_tvDetail = 2131165257;
			
			// aapt resource value: 0x7f07004b
			public const int MDS_tvSchedule = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int MDS_tvTrailer = 2131165261;
			
			// aapt resource value: 0x7f0700a2
			public const int MLTI_imgLeft = 2131165346;
			
			// aapt resource value: 0x7f070093
			public const int MLTI_imgMovie = 2131165331;
			
			// aapt resource value: 0x7f0700a0
			public const int MLTI_linImageHolderChild = 2131165344;
			
			// aapt resource value: 0x7f07009f
			public const int MLTI_linImageHolderParent = 2131165343;
			
			// aapt resource value: 0x7f070092
			public const int MLTI_linTopContainer = 2131165330;
			
			// aapt resource value: 0x7f0700a1
			public const int MLTI_relControlHolder = 2131165345;
			
			// aapt resource value: 0x7f0700a3
			public const int MLTI_tvBuyTicket = 2131165347;
			
			// aapt resource value: 0x7f07009d
			public const int MLTI_tvCinemaAndDateTime = 2131165341;
			
			// aapt resource value: 0x7f070096
			public const int MLTI_tvDurationAndGenre = 2131165334;
			
			// aapt resource value: 0x7f070095
			public const int MLTI_tvMTRCBRating = 2131165333;
			
			// aapt resource value: 0x7f070094
			public const int MLTI_tvMovieDisplayTitle = 2131165332;
			
			// aapt resource value: 0x7f07009c
			public const int MLTI_tvMovieScreening = 2131165340;
			
			// aapt resource value: 0x7f070099
			public const int MLTI_tvPurchasedOn = 2131165337;
			
			// aapt resource value: 0x7f070098
			public const int MLTI_tvPurchasedTickets = 2131165336;
			
			// aapt resource value: 0x7f07009e
			public const int MLTI_tvSwipeToSeeQrCode = 2131165342;
			
			// aapt resource value: 0x7f07009a
			public const int MLTI_tvTotalAmount = 2131165338;
			
			// aapt resource value: 0x7f070097
			public const int MLTI_tvTransactionDetail = 2131165335;
			
			// aapt resource value: 0x7f070020
			public const int MRS_btnOk = 2131165216;
			
			// aapt resource value: 0x7f07001c
			public const int MRS_scrollView = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int MRS_tvDetail = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int MRS_tvRating = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int MRS_tvRatingCode = 2131165213;
			
			// aapt resource value: 0x7f07009b
			public const int MTLI_imgLeft = 2131165339;
			
			// aapt resource value: 0x7f070058
			public const int MT_andC_scrollView = 2131165272;
			
			// aapt resource value: 0x7f07008e
			public const int MT_fraLayout = 2131165326;
			
			// aapt resource value: 0x7f07007e
			public const int MT_imgMovie = 2131165310;
			
			// aapt resource value: 0x7f070087
			public const int MT_linBase = 2131165319;
			
			// aapt resource value: 0x7f070088
			public const int MT_linDetail = 2131165320;
			
			// aapt resource value: 0x7f07008f
			public const int MT_linDetailContent = 2131165327;
			
			// aapt resource value: 0x7f07008a
			public const int MT_linSchedule = 2131165322;
			
			// aapt resource value: 0x7f070090
			public const int MT_linScheduleContent = 2131165328;
			
			// aapt resource value: 0x7f07008c
			public const int MT_linTrailer = 2131165324;
			
			// aapt resource value: 0x7f070091
			public const int MT_linTrailerContent = 2131165329;
			
			// aapt resource value: 0x7f07007f
			public const int MT_relControlHolder = 2131165311;
			
			// aapt resource value: 0x7f070083
			public const int MT_relMiscHolder = 2131165315;
			
			// aapt resource value: 0x7f070081
			public const int MT_relUserRatingHolder = 2131165313;
			
			// aapt resource value: 0x7f070086
			public const int MT_tvBuyTicket = 2131165318;
			
			// aapt resource value: 0x7f070089
			public const int MT_tvDetail = 2131165321;
			
			// aapt resource value: 0x7f070084
			public const int MT_tvMTRCBRating = 2131165316;
			
			// aapt resource value: 0x7f070085
			public const int MT_tvMiscDetails = 2131165317;
			
			// aapt resource value: 0x7f070080
			public const int MT_tvMovieDisplayTitle = 2131165312;
			
			// aapt resource value: 0x7f07008b
			public const int MT_tvSchedule = 2131165323;
			
			// aapt resource value: 0x7f07008d
			public const int MT_tvTrailer = 2131165325;
			
			// aapt resource value: 0x7f070082
			public const int MT_tvUserRating = 2131165314;
			
			// aapt resource value: 0x7f070060
			public const int MTandCDetail_tvCinema = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int MTandCDetail_tvCinemaValue = 2131165281;
			
			// aapt resource value: 0x7f07007b
			public const int MTandCDetail_tvCreditCardNumberValue = 2131165307;
			
			// aapt resource value: 0x7f070031
			public const int MTandCDetail_tvInstruction = 2131165233;
			
			// aapt resource value: 0x7f07007c
			public const int MTandCDetail_tvNameOnCard = 2131165308;
			
			// aapt resource value: 0x7f07007d
			public const int MTandCDetail_tvNameOnCardValue = 2131165309;
			
			// aapt resource value: 0x7f07007a
			public const int MTandCDetail_tvPaidViaCreditCard = 2131165306;
			
			// aapt resource value: 0x7f07006a
			public const int MTandCDetail_tvQuantity = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int MTandCDetail_tvQuantityValue = 2131165291;
			
			// aapt resource value: 0x7f070062
			public const int MTandCDetail_tvScheduleDate = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int MTandCDetail_tvScheduleValue = 2131165283;
			
			// aapt resource value: 0x7f070070
			public const int MTandCDetail_tvSeatNos = 2131165296;
			
			// aapt resource value: 0x7f070071
			public const int MTandCDetail_tvSeatNosValue = 2131165297;
			
			// aapt resource value: 0x7f070066
			public const int MTandCDetail_tvSeating = 2131165286;
			
			// aapt resource value: 0x7f070067
			public const int MTandCDetail_tvSeatingValue = 2131165287;
			
			// aapt resource value: 0x7f070072
			public const int MTandCDetail_tvSource = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int MTandCDetail_tvSourceValue = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int MTandCDetail_tvStatus = 2131165300;
			
			// aapt resource value: 0x7f070075
			public const int MTandCDetail_tvStatusValue = 2131165301;
			
			// aapt resource value: 0x7f070047
			public const int MTandCDetail_tvTermAndCondition = 2131165255;
			
			// aapt resource value: 0x7f07005e
			public const int MTandCDetail_tvTheater = 2131165278;
			
			// aapt resource value: 0x7f07005f
			public const int MTandCDetail_tvTheaterValue = 2131165279;
			
			// aapt resource value: 0x7f070068
			public const int MTandCDetail_tvTicketPrice = 2131165288;
			
			// aapt resource value: 0x7f070069
			public const int MTandCDetail_tvTicketPriceValue = 2131165289;
			
			// aapt resource value: 0x7f070064
			public const int MTandCDetail_tvTime = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int MTandCDetail_tvTimeValue = 2131165285;
			
			// aapt resource value: 0x7f07006e
			public const int MTandCDetail_tvTotalAmountDue = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int MTandCDetail_tvTotalAmountDueValue = 2131165295;
			
			// aapt resource value: 0x7f07003e
			public const int MTandCDetail_tvTransaction = 2131165246;
			
			// aapt resource value: 0x7f070078
			public const int MTandCDetail_tvTransactionDate = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int MTandCDetail_tvTransactionDateValue = 2131165305;
			
			// aapt resource value: 0x7f070076
			public const int MTandCDetail_tvTransactionNumber = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int MTandCDetail_tvTransactionNumberValue = 2131165303;
			
			// aapt resource value: 0x7f07002f
			public const int MTandCDetail_tvTransactionStatus = 2131165231;
			
			// aapt resource value: 0x7f07006c
			public const int MTandCDetail_tvWebAdminFee = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int MTandCDetail_tvWebAdminFeeValue = 2131165293;
			
			// aapt resource value: 0x7f07005a
			public const int MTandC_imgQrCode = 2131165274;
			
			// aapt resource value: 0x7f07005d
			public const int MTandC_linBase = 2131165277;
			
			// aapt resource value: 0x7f070033
			public const int MTandC_tvCinema = 2131165235;
			
			// aapt resource value: 0x7f070059
			public const int MTandC_tvConfirmationCode = 2131165273;
			
			// aapt resource value: 0x7f070044
			public const int MTandC_tvCreditCardNumber = 2131165252;
			
			// aapt resource value: 0x7f070030
			public const int MTandC_tvInstruction = 2131165232;
			
			// aapt resource value: 0x7f07005c
			public const int MTandC_tvMTRCB = 2131165276;
			
			// aapt resource value: 0x7f07005b
			public const int MTandC_tvMovieTitle = 2131165275;
			
			// aapt resource value: 0x7f070045
			public const int MTandC_tvNameOnCard = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int MTandC_tvNameOnCardValue = 2131165254;
			
			// aapt resource value: 0x7f070043
			public const int MTandC_tvPaidViaCreditCard = 2131165251;
			
			// aapt resource value: 0x7f070038
			public const int MTandC_tvQuantity = 2131165240;
			
			// aapt resource value: 0x7f070034
			public const int MTandC_tvScheduleDate = 2131165236;
			
			// aapt resource value: 0x7f07003b
			public const int MTandC_tvSeatNos = 2131165243;
			
			// aapt resource value: 0x7f070036
			public const int MTandC_tvSeating = 2131165238;
			
			// aapt resource value: 0x7f07003c
			public const int MTandC_tvSource = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int MTandC_tvStatus = 2131165245;
			
			// aapt resource value: 0x7f070032
			public const int MTandC_tvTheater = 2131165234;
			
			// aapt resource value: 0x7f070037
			public const int MTandC_tvTicketPrice = 2131165239;
			
			// aapt resource value: 0x7f070035
			public const int MTandC_tvTime = 2131165237;
			
			// aapt resource value: 0x7f07003a
			public const int MTandC_tvTotalAmountDue = 2131165242;
			
			// aapt resource value: 0x7f070041
			public const int MTandC_tvTransactionDate = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int MTandC_tvTransactionDateValue = 2131165250;
			
			// aapt resource value: 0x7f07003f
			public const int MTandC_tvTransactionNumber = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int MTandC_tvTransactionNumberValue = 2131165248;
			
			// aapt resource value: 0x7f070039
			public const int MTandC_tvWebAdminFee = 2131165241;
			
			// aapt resource value: 0x7f07000f
			public const int Master_fraContent = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int Master_imgLogo = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int Master_imgSearch = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int Master_linHeader = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int Master_relCheckIn = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int Master_relHeader = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int Master_relMovie = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int Master_relMyAccount = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int Master_relPromos = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int Master_tvBackNavi = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int Master_tvCheckIn = 2131165203;
			
			// aapt resource value: 0x7f07000b
			public const int Master_tvHeaderTitle = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int Master_tvMovie = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int Master_tvMyAccount = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int Master_tvPromos = 2131165207;
			
			// aapt resource value: 0x7f07000d
			public const int Master_tvScreenTitle = 2131165197;
			
			// aapt resource value: 0x7f070052
			public const int MovieHome_imgMovie = 2131165266;
			
			// aapt resource value: 0x7f070054
			public const int MovieScrollHome_hsvScroll = 2131165268;
			
			// aapt resource value: 0x7f070056
			public const int MovieScrollHome_imgLeft = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int MovieScrollHome_imgRight = 2131165271;
			
			// aapt resource value: 0x7f070055
			public const int MovieScrollHome_linLayout = 2131165269;
			
			// aapt resource value: 0x7f070053
			public const int MovieScrollHome_tvDate = 2131165267;
			
			// aapt resource value: 0x7f07001b
			public const int NoMRS_btnOk = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int NoMRS_txtTitle = 2131165217;
			
			// aapt resource value: 0x7f0700a4
			public const int PromoDetail_imgMovie = 2131165348;
			
			// aapt resource value: 0x7f0700a6
			public const int PromoDetail_tvPromoDuration = 2131165350;
			
			// aapt resource value: 0x7f0700a7
			public const int PromoDetail_tvPromoDurationValue = 2131165351;
			
			// aapt resource value: 0x7f0700a8
			public const int PromoDetail_tvPromoMechanics = 2131165352;
			
			// aapt resource value: 0x7f0700a5
			public const int PromoDetail_tvPromoTitle = 2131165349;
			
			// aapt resource value: 0x7f070023
			public const int VerifyPassword_btnOk = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int VerifyPassword_tvTitle = 2131165218;
			
			// aapt resource value: 0x7f0700a9
			public const int myButton = 2131165353;
			
			// aapt resource value: 0x7f0700aa
			public const int pager = 2131165354;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_LoginMasterPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_MasterPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_SplashScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Dialog_Instruction = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Dialog_MTRCBRating = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Dialog_NoMTRCBRating = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Dialog_VerifyPassword = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DialogVerifyPassword = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Frag_CheckIn = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Frag_LogIn_One = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Frag_LogIn_Two = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Frag_Movie_TermsAndConditionDetail = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Frag_MovieDetailScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Frag_MovieDetailTab = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Frag_MovieHome = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Frag_MovieScrollHome = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Frag_MovieTermsAndCondition = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Frag_MovieTermsAndConditionDetail = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Frag_MovieTicket = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Frag_MyAcctTicketListItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Frag_MyTicketListItem = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Frag_Promo = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Main = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int SeatPlanInstructionScreen = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ViewPager_XML = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int DialogTheme = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int bt_detail_screen_tab_page_style = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bt_detail_screen_text_tab_style = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int rel_style = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int style_fill_parent = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int style_main_navigation_button = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int style_termsAndConditionTextView = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int style_termsAndConditionTextView_values = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int style_wrap_content = 2131034120;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
